#use_frameworks!

platform :ios, '9.0'

target 'CPersonalCategoryKit_Example' do
  pod 'CPersonalCategoryKit', :path => '../'

  target 'CPersonalCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
